version: '3.8'

services:
  poolcontroller:
    image: tagyoureit/nodejs-poolcontroller:latest
    container_name: poolcontroller
    restart: always
    group_add:
      - dialout
    devices:
      - /dev/ttyUSB0
    ports:
      - "4200:4200"
    volumes:
      - /data/poolcontroller/config.json:/app/config.json
      - /data/poolcontroller/data:/app/data
    #build:
    #  context: .  # Specify the current directory as the build context
    #  dockerfile: Dockerfile.linux  # Use Dockerfile.linux for the build
    # Add other configuration options as needed

  poolcontroller-armv7:
    image: tagyoureit/nodejs-poolcontroller-armv7:latest
    container_name: poolcontroller-armv7
    restart: always
    ports:
      - "4200:4200"
    volumes:
      - /data/poolcontroller/config.json:/app/config.json
      - /data/poolcontroller/data:/app/data
    #build:
    #  context: .  # Specify the current directory as the build context
    #  dockerfile: Dockerfile.linux  # Use Dockerfile.linux for the build
    # Add other configuration options for ARMv7 architecture

  poolcontroller-armv6:
    image: tagyoureit/nodejs-poolcontroller-armv6:latest
    container_name: poolcontroller-armv6
    restart: always
    ports:
      - "4200:4200"
    volumes:
      - /data/poolcontroller/config.json:/app/config.json
      - /data/poolcontroller/data:/app/data
    #build:
    #  context: .  # Specify the current directory as the build context
    #  dockerfile: Dockerfile.linux  # Use Dockerfile.linux for the build
    # Add other configuration options for ARMv6 architecture
