name: Publish Docker Image - Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:
    

jobs:
  build-and-push-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      -
          # Add support for more platforms with QEMU (optional)
          # https://github.com/docker/setup-qemu-action
          name: Set up QEMU
          uses: docker/setup-qemu-action@v3
      -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Windows Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.windows
          push: true
          tags: |
            tagyoureit/nodejs-poolcontroller:windows-latest
          platforms: windows/amd64
