name: Publish Docker Image - Ubuntu

on:
  push:
    branches:
      - main
      - docker
  workflow_dispatch:
    

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Checkout code from separate repo
        uses: actions/checkout@v3
        with:
          repository: rstrouse/nodejs-poolcontroller-dashpanel  # Replace with the username and repository name of the separate repository
          ref: main  # Specify the branch or tag to pull from
          path: nodejs-poolcontroller-dashpanel  # Specify the directory to checkout the code into

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push njsPC Linux Docker image (x86_64)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./.docker/Dockerfile.linux
          push: true
          tags: |
            tagyoureit/nodejs-poolcontroller:latest

      - name: Build and push njsPC-dP Linux Docker image (x86_64)
        uses: docker/build-push-action@v4
        with:
          context: nodejs-poolcontroller-dashpanel
          file: ./.docker/Dockerfile.linux
          push: true
          tags: |
            rstrouse/nodejs-poolcontroller-dashpanel:latest

      # - name: Build and push ARMv7 Docker image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     file: ./.docker/Dockerfile.armv7  # Adjust the path to your ARMv7 Dockerfile
      #     push: true
      #     tags: |
      #       tagyoureit/nodejs-poolcontroller-armv7:latest

      # - name: Build and push ARMv6 Docker image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     file: ./.docker/Dockerfile.armv6  # Adjust the path to your ARMv6 Dockerfile
      #     push: true
      #     tags: |
      #       tagyoureit/nodejs-poolcontroller-armv6:latest
